// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb1RPn_nbttOg3sxNq1xih6wrRXx1BiNE',
    appId: '1:379833102691:web:8289888193e8f85fff2356',
    messagingSenderId: '379833102691',
    projectId: 'todo-6c0f7',
    authDomain: 'todo-6c0f7.firebaseapp.com',
    storageBucket: 'todo-6c0f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDOlhrxuuaJli0pj_Au3-y_eNH5C183f4',
    appId: '1:379833102691:android:9f32142cb5c94aacff2356',
    messagingSenderId: '379833102691',
    projectId: 'todo-6c0f7',
    storageBucket: 'todo-6c0f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByEPOmGFcCZw0kF-EAK6ohUsrHQn3UrZo',
    appId: '1:379833102691:ios:a30fb52a5bf603ffff2356',
    messagingSenderId: '379833102691',
    projectId: 'todo-6c0f7',
    storageBucket: 'todo-6c0f7.appspot.com',
    iosBundleId: 'com.nabik.baburam.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByEPOmGFcCZw0kF-EAK6ohUsrHQn3UrZo',
    appId: '1:379833102691:ios:4d67c5d2bfa3b815ff2356',
    messagingSenderId: '379833102691',
    projectId: 'todo-6c0f7',
    storageBucket: 'todo-6c0f7.appspot.com',
    iosBundleId: 'com.nabik.baburam.todo.RunnerTests',
  );
}
